### ISSUE TITLE
请问如何将模板include行为用其他方式代替

### ISSUE THREAD

**Issue by staugur** [greyli/flask-china#4]
Hey，恰巧发现您是官方开发成员，故提一个“奇葩”的问题，万望解答！

---

### 期望的行为

我想将“flask在模板文件include”改为“直接在flask服务端实现”，即：

当前(模板中include)
```python
{% include hf %}
```

修改后(模板中执行函数自动include)
```python
{{ func() }}
```

### 环境版本

* 操作系统：any
* Python：any
* Flask：any

**Comment by greyli** [comment]
> 我想将“flask在模板文件include”改为“直接在flask服务端实现”

模板渲染本身就是服务器端的操作，在发出HTTP响应时，模板文件已经被渲染为HTML文件。请问这样做的目的是什么？

**Comment by staugur** [comment]
是的，我想在一个服务端插件中使用"包含"扩展模板的内容

**Comment by greyli** [comment]
为什么不能直接用原有的include标签？

**Comment by staugur** [comment]
我是想看看能不能动态地扩展一个已有的应用，像[这个](https://flask-plugins.readthedocs.io/en/latest/#events)一样

**Comment by greyli** [comment]
那你可以在函数里返回对应的模板，比如：
```html
{{ get_foo() }}
```
函数定义：
```py
def get_foo():
    return render_template('foo.html')
```

**Comment by staugur** [comment]
哦！我测试一下！

**Comment by greyli** [comment]
好的，那个render_template需要从flask包导入。

**Comment by staugur** [comment]
赞一个！实现了我的想法，不过还是要加一个Markup，不然不解析HTML代码。

**Comment by staugur** [comment]
不过也发现了一个问题：原先用include时的模板页面是通过render_template渲染的，可能带有额外数据，此时改为这种方法便获取不到原先render的数据，也是美中不足。

**Comment by greyli** [comment]
或许可以考虑在函数调用里传入这些数据作为参数？

**Comment by staugur** [comment]
是的，我单独加了**context传给render_template以解决需要额外数据的问题
