### ISSUE TITLE
flask.cli.NoAppException

### ISSUE THREAD

**Issue by new911small** [greyli/flask-china#7]
flask.cli.NoAppException: Could not import "app".

windows系统，找了相关解决办法，都不行，忘解答谢谢

**Comment by greyli** [comment]
请提供：

* 相关代码
* 启动命令，执行命令的工作目录
* 完整的错误输出
* 启动方式
* Flask 版本

**Comment by new911small** [comment]
具体信息已上传此链接，望回复，谢谢
https://www.cnblogs.com/daqingzi/p/10517175.html

**Comment by greyli** [comment]
把 .flaskenv 放到 hello 目录下面，和 apples.py 同级，然后把当前目录切换到 hello 目录，再执行 flask run。

**Comment by new911small** [comment]
你好，可以问下flask+pyecharts的问题么，我目前是通过pyecharts生成了一个页面，想要用两一个页面加载这个pyecharts生成的页面，但是出现了如下报错jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 1100277，该怎么解决，具体详情图片链接如下：https://www.cnblogs.com/daqingzi/p/10867647.html

**Comment by greyli** [comment]
新的问题请创建新的 issue。另外，请问上面的问题解决了吗？

**Comment by new911small** [comment]
好的，我新建一个问题，目前还没有





------------------ 原始邮件 ------------------
发件人: "Grey Li"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 中午11:13
收件人: "greyli/flask-china"<flask-china@noreply.github.com>;
抄送: "慢半拍"<1920162283@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [greyli/flask-china] flask.cli.NoAppException (#7)




新的问题请创建新的 issue。另外，请问上面的问题解决了吗？

**Comment by greyli** [comment]
试了我说的方法了吗？

**Comment by new911small** [comment]
不好意思，不是上面一个那个问题了，上面那个问题已经解决了
我新建一个问题，是jinja2和pyecharts的"\\"问题，目前问题还没有解决





------------------ 原始邮件 ------------------
发件人: "Grey Li"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 中午11:25
收件人: "greyli/flask-china"<flask-china@noreply.github.com>;
抄送: "慢半拍"<1920162283@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [greyli/flask-china] flask.cli.NoAppException (#7)




按照我说的方法没用？

**Comment by greyli** [comment]
嗯，如果问题解决，请反馈一下。

**Comment by new911small** [comment]
第一个问题，按照方法已经解决，谢谢

**Comment by greyli** [comment]
不客气。
