### ISSUE TITLE
flask+pyecharts

### ISSUE THREAD

**Issue by new911small** [greyli/flask-china#8]
你好，可以问下flask+pyecharts的问题么，我目前是通过pyecharts生成了一个页面，想要用两一个页面加载这个pyecharts生成的页面，但是出现了如下报错jinja2.exceptions.TemplateSyntaxError: unexpected char '\' at 1100277，该怎么解决，具体详情图片链接如下：https://www.cnblogs.com/daqingzi/p/10867647.html

### 期望的行为
用pyecharts生成的页面可以用另一个html加载出来

描述你想获得的效果。
上面链接有想要实现的图片
```python
复制最小化的相关代码到这里。
```

描述实际发生了什么。

```pytb
如果有异常，复制完整的回溯信息到这里。
```

### 环境版本

* 操作系统：windows
* Python：3.6
* Flask：1.0.2

如果问题和扩展相关，请一并写出扩展的版本。

**Comment by new911small** [comment]
你好，目前我的问题已经解决了，通过django实现，上面的问题应该是jinja2和echarts里的"//"不兼容问题

**Comment by greyli** [comment]
好的。我一般会直接用 Echarts，渲染模板的时候传入数据，在模板里把数据转换成 JSON 格式（用 tojson 过滤器）。
